# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PEiUIhZxr3dhmYQCRMiLVJRS6myCoP3C
"""

import numpy as np
from flask import Flask,request,jsonify,render_template
import pickle
import pandas as pd

dataset=pd.read_csv('Social_Network_Ads.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
from sklearn.model_selection import train_test_split
x_train0,_,_,_=train_test_split(x,y,test_size=0.2,stratify=y,random_state=0)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train0)

app=Flask(__name__)
model=pickle.load(open('model.pkl','rb'))
#scaling=pickle.load(open('scaling.pkl','rb'))
@app.route('/')
def home():
  return render_template('index.html')
@app.route('/predict',methods=['POST'])
def predict():
  int_features=[int(x) for x in request.form.values()]
  final_features=[np.array(int_features)]
  final_features=sc.transform(final_features)
  prediction=model.predict(final_features)
  output=prediction
  if(output.sum()==1):
    output='Yes'
  else:
    output='No'
  return render_template('index.html',prediction_text='Customer purchase status: '+str(output))

if __name__ =="__main__":
  app.run(debug=True)

